import { state } from "./state.js";
import { showToast, formatDate } from "./utils.js";

// ==========================================================================
// POWERPOINT EXPORT (PptxGenJS)
// ==========================================================================
// This relies on PptxGenJS library being loaded in index.html via CDN.

export async function exportPPTX() {
    // 1. Verify Library Availability
    if (typeof PptxGenJS === 'undefined') {
        showToast("Export library loading... check internet or try again.", "error");
        return;
    }

    // 2. Verify Data
    const d = state.projectData;
    if (!d) {
        showToast("No project data to export.", "error");
        return;
    }

    showToast("Generating PowerPoint...", "info");

    // 3. Initialize Presentation
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_16x9';
    pres.title = d.meta.title;
    pres.subject = "Quality Improvement Project";
    
    // --- BRANDING COLORS ---
    const RCEM_PURPLE = "2d2e83";
    const RCEM_ORANGE = "f36f21";
    const SLATE_DARK = "0f172a";
    const SLATE_LIGHT = "F1F5F9";

    // =======================================
    // SLIDE 1: TITLE SLIDE
    // =======================================
    let slide = pres.addSlide();
    slide.background = { color: SLATE_LIGHT };
    
    // Title
    slide.addText(d.meta?.title || "Quality Improvement Project", { 
        x: 1, y: 2.5, w: '80%', 
        fontSize: 32, bold: true, color: RCEM_PURPLE, align: 'left'
    });
    
    // Subtitle / Date
    slide.addText(`Generated by RCEM QIP Assistant | ${new Date().toLocaleDateString()}`, { 
        x: 1, y: 4, w: '80%', 
        fontSize: 14, color: "64748B", align: 'left'
    });
    
    // Author
    if(d.teamMembers && d.teamMembers.length > 0) {
        slide.addText(`Project Lead: ${d.teamMembers[0].name}`, {
            x: 1, y: 5, w: '50%', fontSize: 12, color: RCEM_ORANGE
        });
    }

    // =======================================
    // SLIDE 2: CHARTER (Problem & Aim)
    // =======================================
    slide = pres.addSlide();
    
    // Header
    slide.addText("Project Charter", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: RCEM_PURPLE });
    
    // Problem Section
    slide.addText("Problem Definition", { x: 0.5, y: 1.5, fontSize: 14, bold: true, color: RCEM_ORANGE });
    slide.addText(d.checklist?.problem_desc || "No problem defined.", { 
        x: 0.5, y: 1.8, w: 9, h: 1.2, 
        fontSize: 12, color: SLATE_DARK, 
        shape: pres.ShapeType.rect, fill: "FFFFFF", line: { color: "E2E8F0" }, 
        valign: 'top' 
    });
    
    // Aim Section
    slide.addText("SMART Aim", { x: 0.5, y: 3.5, fontSize: 14, bold: true, color: RCEM_ORANGE });
    slide.addText(d.checklist?.aim || "No aim defined.", { 
        x: 0.5, y: 3.8, w: 9, h: 1.2, 
        fontSize: 14, bold: true, color: "4338CA", 
        shape: pres.ShapeType.rect, fill: "EEF2FF", line: { color: "C7D2FE" }, 
        valign: 'middle' 
    });

    // =======================================
    // SLIDE 3: DIAGNOSIS (Driver Diagram)
    // =======================================
    slide = pres.addSlide();
    slide.addText("Driver Diagram", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: RCEM_PURPLE });
    
    const drivers = d.drivers || { primary: [], secondary: [], changes: [] };
    
    // We visualize this as lists for simplicity in PPTX
    // Primary
    slide.addText("Primary Drivers", { x: 0.5, y: 1.2, fontSize: 14, bold: true });
    let yPos = 1.6;
    drivers.primary.forEach(p => {
        if(yPos > 6.5) return;
        slide.addText(p, { 
            x: 0.5, y: yPos, w: 3, h: 0.8, 
            fontSize: 12, fill: "EFF6FF", border: { pt: 1, color: "BFDBFE" }, align: 'center' 
        });
        yPos += 1;
    });

    // Secondary
    slide.addText("Secondary Drivers", { x: 3.7, y: 1.2, fontSize: 14, bold: true });
    yPos = 1.6;
    drivers.secondary.forEach(s => {
        if(yPos > 6.5) return;
        slide.addText(s, { 
            x: 3.7, y: yPos, w: 3, h: 0.8, 
            fontSize: 12, fill: "F0F9FF", border: { pt: 1, color: "BAE6FD" }, align: 'center' 
        });
        yPos += 1;
    });
    
    // Changes
    slide.addText("Change Ideas", { x: 6.9, y: 1.2, fontSize: 14, bold: true });
    yPos = 1.6;
    drivers.changes.forEach(c => {
        if(yPos > 6.5) return;
        slide.addText(c, { 
            x: 6.9, y: yPos, w: 2.6, h: 0.8, 
            fontSize: 12, fill: "ECFDF5", border: { pt: 1, color: "A7F3D0" }, align: 'center' 
        });
        yPos += 1;
    });

    // =======================================
    // SLIDE 4: RESULTS (Chart Snapshot)
    // =======================================
    slide = pres.addSlide();
    slide.addText("Results", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: RCEM_PURPLE });
    
    // Attempt to capture the chart canvas
    // NOTE: The chart must be visible in the DOM for this to work.
    const canvas = document.getElementById('mainChart');
    if (canvas) {
        try {
            const dataUrl = canvas.toDataURL('image/png');
            slide.addImage({ data: dataUrl, x: 1, y: 1.2, w: 8, h: 4.5 });
            
            // Add Interpretation Text
            if (d.checklist?.results_text) {
                slide.addText(d.checklist.results_text, {
                    x: 1, y: 6, w: 8, h: 1,
                    fontSize: 11, italic: true, color: "475569",
                    shape: pres.ShapeType.rect, fill: "F1F5F9"
                });
            }
        } catch (e) {
            slide.addText("Chart image capture failed (Canvas tainted or hidden).", { x: 1, y: 3, color: "red" });
        }
    } else {
        slide.addText("Chart not currently active in view. Go to Data view to capture.", { x: 1, y: 3, italic: true });
    }

    // =======================================
    // SLIDE 5: LEADERSHIP LOG (New Feature)
    // =======================================
    slide = pres.addSlide();
    slide.addText("Leadership & Engagement Log", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: RCEM_PURPLE });
    
    if (d.leadershipLogs && d.leadershipLogs.length > 0) {
        // Prepare table data
        const rows = d.leadershipLogs.map(l => [l.date, l.note]);
        // Add Header Row
        rows.unshift(["Date", "Activity / Engagement / Note"]); 
        
        slide.addTable(rows, {
            x: 0.5, y: 1.5, w: 9,
            colW: [2, 7], // 2 inches date, 7 inches note
            fontSize: 11,
            border: { pt: 1, color: "E2E8F0" },
            fill: { color: "FFFFFF" },
            headerStyles: { fill: { color: RCEM_PURPLE }, color: "FFFFFF", bold: true },
            rowH: 0.5
        });
    } else {
        slide.addText("No leadership logs recorded.", { 
            x: 0.5, y: 2, fontSize: 12, italic: true, color: "94A3B8" 
        });
    }

    // =======================================
    // SLIDE 6+: PDSA CYCLES
    // =======================================
    if (d.pdsa && d.pdsa.length > 0) {
        d.pdsa.forEach((p, i) => {
            slide = pres.addSlide();
            slide.addText(`PDSA Cycle ${i+1}: ${p.title || 'Untitled'}`, { 
                x: 0.5, y: 0.5, fontSize: 20, bold: true, color: RCEM_PURPLE 
            });
            slide.addText(`${p.start || ''} - ${p.end || ''}`, {
                x: 0.5, y: 0.9, fontSize: 12, color: "64748B"
            });
            
            // 4-Quadrant Grid
            // PLAN
            slide.addText("PLAN", { 
                x: 0.5, y: 1.2, w: 4.5, h: 0.4, 
                fontSize: 12, bold: true, fill: "DBEAFE", color: "1E3A8A" 
            });
            slide.addText(p.desc || "No plan details.", { 
                x: 0.5, y: 1.6, w: 4.5, h: 2, 
                fontSize: 11, fill: "F8FAFC", valign: "top", border: { pt: 0.5, color: "DBEAFE" } 
            });

            // DO
            slide.addText("DO", { 
                x: 5.1, y: 1.2, w: 4.5, h: 0.4, 
                fontSize: 12, bold: true, fill: "FFEDD5", color: "9A3412" 
            });
            slide.addText(p.do || "No execution details.", { 
                x: 5.1, y: 1.6, w: 4.5, h: 2, 
                fontSize: 11, fill: "F8FAFC", valign: "top", border: { pt: 0.5, color: "FFEDD5" } 
            });

            // STUDY
            slide.addText("STUDY", { 
                x: 0.5, y: 3.8, w: 4.5, h: 0.4, 
                fontSize: 12, bold: true, fill: "F3E8FF", color: "6B21A8" 
            });
            slide.addText(p.study || "No analysis.", { 
                x: 0.5, y: 4.2, w: 4.5, h: 2, 
                fontSize: 11, fill: "F8FAFC", valign: "top", border: { pt: 0.5, color: "F3E8FF" } 
            });

            // ACT
            slide.addText("ACT", { 
                x: 5.1, y: 3.8, w: 4.5, h: 0.4, 
                fontSize: 12, bold: true, fill: "DCFCE7", color: "166534" 
            });
            slide.addText(p.act || "No next steps.", { 
                x: 5.1, y: 4.2, w: 4.5, h: 2, 
                fontSize: 11, fill: "F8FAFC", valign: "top", border: { pt: 0.5, color: "DCFCE7" } 
            });
        });
    }

    // 4. Save File
    const safeTitle = d.meta.title.replace(/[^a-z0-9]/gi, '_').substring(0, 30);
    pres.writeFile({ fileName: `QIP_${safeTitle}.pptx` });
    showToast("Download started", "success");
}


// ==========================================================================
// PRINT POSTER (Browser Print Helper)
// ==========================================================================

/**
 * Standard Print
 */
export function printPoster() {
    // Force a redraw of the chart canvas onto the printable area if needed.
    const chartCanvas = document.getElementById('poster-chart');
    const mainCanvas = document.getElementById('mainChart');
    
    if (chartCanvas && mainCanvas) {
        // Clone the main chart image to the poster's canvas
        const destCtx = chartCanvas.getContext('2d');
        destCtx.drawImage(mainCanvas, 0, 0, chartCanvas.width, chartCanvas.height);
    }
    
    window.print();
}

/**
 * Prints ONLY the Poster content, hiding everything else
 * This relies on a 'printing-poster-mode' CSS class in styles.css that hides sidebar, nav, etc.
 */
export function printPosterOnly() {
    const poster = document.getElementById('view-full'); // We use the Full View as the "Poster"
    if (!poster) { 
        showToast("Go to 'Full Project' view first", "error"); 
        return; 
    }
    
    document.body.classList.add('printing-poster-mode');
    window.print();
    // Remove class after print dialog closes (in most browsers this happens immediately or pauses JS)
    // To be safe, we remove it after a short delay or listen for afterprint
    setTimeout(() => {
        document.body.classList.remove('printing-poster-mode');
    }, 1000);
}
